apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gs-spring-boot-k8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gs-spring-boot-k8s
          servicePort: 8001